### ISSUE TITLE
9.18.0 release not on packagist

### ISSUE THREAD

**Issue by arnegroskurth** [m4tthumphrey/php-gitlab-api#556] opened 2020-07-13 11:03 UTC
The 9.18.0 release is not available on packagist: https://packagist.org/packages/m4tthumphrey/php-gitlab-api

Is the hook maybe not set up correctly? https://packagist.org/about#how-to-update-packages

**Comment by GrahamCampbell** [comment] 2020-07-13 11:09
The hook is setup and it claims to be working:

![image](https://user-images.githubusercontent.com/2829600/87298170-a7424a00-c501-11ea-86c0-a4334e6cc579.png)

**Comment by GrahamCampbell** [comment] 2020-07-13 11:14
I'm not sure what's going on here. I've triggered a manual update, so the release should be available now.

**Comment by GrahamCampbell** [comment] 2020-07-13 11:18
Ok, I think the root cause is fixed now (they lied about it being auto-updated :trollface:). Thanks for the report!

**Closed as completed by GrahamCampbell** 2020-07-13 11:18 UTC
